select
  variant_id,
  platform,
  signed_in,
  new_visitor,
  engaged_w_reviews,
  converted,
  count(distinct visit_id) as visits, 
  count(distinct listing_id) as listings, 
  sum(listing_views) as listing_views, 
  sum(reviews_seen) as reviews_seen, 
  sum(reviews_top_container_seen) as reviews_top_container_seen, 
  sum(listing_page_review_engagements) as listing_page_review_engagements, 
  sum(paginations) as paginations, 
  sum(photo_opens) as photo_opens, 
  sum(review_sorts) as review_sorts, 
  sum(cat_tag_clicks) as cat_tag_clicks, 
  sum(cat_tags_seen) as cat_tags_seen, 
  sum(toggle_opens) as toggle_opens, 
  count(distinct case when viewed_listing > 0 then visit_id end) as visit_w_lv,
  count(distinct case when saw_reviews > 0 then visit_id end) as visit_w_reviews_seen,
  count(distinct case when has_top_container > 0 then visit_id end) as visit_w_top_container,
  count(distinct case when has_review_engagement > 0 then visit_id end) as visit_w_review_engagement,
  count(distinct case when has_paginations > 0 then visit_id end) as visit_w_pagination,
  count(distinct case when has_photo_open > 0 then visit_id end) as visit_w_photo_open,
  count(distinct case when has_review_sort > 0 then visit_id end) as visit_w_review_sort,
  count(distinct case when has_cat_tag_click > 0 then visit_id end) as visit_w_cat_tag_click,
  count(distinct case when has_cat_tag_seen > 0 then visit_id end) as visit_w_cat_tag_seen,
  count(distinct case when has_toggle_opens > 0 then visit_id end) as visit_w_toggle_open,
  count(distinct case when converted > 0 then visit_id end) as visit_w_conversion,
from
    etsy-data-warehouse-dev.madelinecollins.segments_and_events 
group by all 
