-------------------------------------------------------------------------------
-- what does engagement + review distribution look like by top category? 
-------------------------------------------------------------------------------
-- active listings, high vs low stakes, listing views, gms coverage, unique visits, conversions, total reviews, review_seen events, review_seen visits, review distrbution by rating
